[package]
name = "bevy_tilt_five"
version = "0.1.0"
edition = "2021"

[dependencies]
libloading = "*"
anyhow = "*"
bevy = "*"

[build-dependencies]
bindgen = "0.63"

[dev-dependencies]
bevy-inspector-egui = "*"
bevy_egui = "*"